services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
  
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  static:
    build: ./requirements/bonus/static
    container_name: static
    restart: always
    ports:
      - "8081:8081"
    networks:
      - inception
  
  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - inception

  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks:
      - inception
    depends_on:
      - wordpress
  
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}
    volumes:
      - wordpress_data:/var/www/wordpress
    ports:
      - "21:21"
      - "40000-40005:40000-40005"
    networks:
      - inception
    depends_on:
      - wordpress

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcuesta-/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcuesta-/data/wordpress
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcuesta-/data/portainer

networks:
  inception:
    driver: bridge