services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
  
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcuesta-/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mcuesta-/data/wordpress

networks:
  inception:
    driver: bridge